name: Python CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # ↓ ここを追加：pytestをインストールする
      - name: Install dependencies
        run: pip install pytest

      - name: Run Test
        run: pytest test_hello.py

      - name: Run Python program
        run: python hello.py
